#!/opt/bin/env bash
#required dependencies can be installed with:
# /opt/bin/opkg update
# /opt/bin/opkg install core-utils coreutils-stat grep dnsmasq bash nano procps-ng-ps
PROCESSES_TO_KILL=( "udhcpd" "/usr/sbin/dnsmasq" )
WAIT_FOR_SERVICES_TO_START=20
WAIT_FOR_SERVICES_TO_START_INCREMENT=2
WAIT_FOR_SERVICE_TO_STOP=5
WAIT_FOR_SERVICE_TO_STOP_INCREMENT=1
LOG_FOLDER="/mnt/sda1/logs/dnsmasq"
LOG_USER="guest"
LOG_GROUP="guest"
OPTBIN="/opt/bin"
OPTSBIN="/opt/sbin"
GREP="${OPTBIN}/grep"
DNSMASQ_FULL="${OPTSBIN}/dnsmasq"
KILLALL="${OPTBIN}/killall"
SLEEP="${OPTBIN}/sleep"
SEQ="${OPTBIN}/seq"
BASENAME="${OPTBIN}/basename"
PS="${OPTBIN}/ps"
ECHO="${OPTBIN}/echo"
MKDIR="${OPTBIN}/mkdir"
RM="${OPTBIN}/rm"
CHOWN="${OPTBIN}/chown"
STAT="${OPTBIN}/stat"
DNSMASQ_ORIG=""

#alias psgrep='ps aux | grep -v "grep" | "${GREP}" -i'

#make the log folder if it doesn't exist
if [ ! -e "${LOG_FOLDER}" ]
then
    "${MKDIR}" -p "${LOG_FOLDER}"
    "${CHOWN}" "${LOG_USER}:${LOG_GROUP}" -R "${LOG_FOLDER}"
elif [ ! -d "${LOG_FOLDER}" ]
then
    #somethings there, and not a directory, remove it
    "${RM}" -rf "${LOG_FOLDER}"
    "${MKDIR}" -p "${LOG_FOLDER}"
    "${CHOWN}" -R "${LOG_USER}:${LOG_GROUP}" "${LOG_FOLDER}"
fi

#make sure it's owned by the right user/group
if [ "$("${STAT}" --format '%U' "${LOG_FOLDER}")" != "${LOG_USER}" ] || [ "$("${STAT}" --format '%G' "${LOG_FOLDER}")" != "${LOG_GROUP}" ]
then
    "${CHOWN}" "${LOG_USER}:${LOG_GROUP}" -R "${LOG_FOLDER}"
fi

wait=${WAIT_FOR_SERVICES_TO_START}
"${ECHO}" -n "Waiting for all services to start, say ${wait}s..."
inc=${WAIT_FOR_SERVICES_TO_START_INCREMENT}
for i in $("${SEQ}" 1 $((wait/inc)))
do
    "${SLEEP}" ${inc}s
    "${ECHO}" -n "$((wait-(i*inc)))s.."
done

"${ECHO}" ""
for process in ${PROCESSES_TO_KILL[@]}
do
    processName="$("${BASENAME}" "${process}")"
    if (( $("${PS}" aux | "${GREP}" -v "grep" | "${GREP}" -i -c "${process}") > 0 ))
    then
        "${ECHO}" "Killing ${processName}..."
        "${KILLALL}" "${processName}"
        retVal=$?
        if (( ${retVal} > 0 ))
        then
            "${ECHO}" "Process ${processName} exists, but was not killed (return value [${retVal}]"
            "${PS}" aux | "${GREP}" -v "grep" | "${GREP}" -i "${process}"
        else
            wait=${WAIT_FOR_SERVICE_TO_STOP}
            "${ECHO}" -n "Waiting for processs to stop, say ${wait}s..."
            inc=${WAIT_FOR_SERVICE_TO_STOP_INCREMENT}
            for i in $("${SEQ}" 1 $((wait/inc)))
            do
                "${SLEEP}" ${inc}s
                "${ECHO}" -n "$((wait-(i*inc)))s.."
            done
            "${ECHO}" ""
            if (( $("${PS}" aux | "${GREP}" -v "grep" | "${GREP}" -i -c "${process}") > 0 ))
            then
                "${ECHO}" "Process ${processName} exists, but was not killed ([$("${PS}" aux | "${GREP}" -v "grep" | "${GREP}" -i -c "${process}")] processes still exist)"
                "${PS}" aux | "${GREP}" -v "grep" | "${GREP}" -i "${process}"
            else
                "${ECHO}" "Process ${processName} was killed successfully"
            fi
        fi
    else
        "${ECHO}" "Process ${processName} doesn't exist, so no need to kill it"
    fi
done

wait=${WAIT_FOR_SERVICE_TO_STOP}
"${ECHO}" -n "Giving things chance to shutdown ${wait}s..."
inc=${WAIT_FOR_SERVICE_TO_STOP_INCREMENT}
for i in $("${SEQ}" 1 $((wait/inc)))
do
    "${SLEEP}" ${inc}s
    "${ECHO}" -n "$((wait-(i*inc)))s.."
done
"${ECHO}" ""
if (( $("${PS}" aux | "${GREP}" -v "grep" | "${GREP}" -i -c "${DNSMASQ_FULL}") > 0 ))
then
    "${ECHO}" "DNSMasq is already running, please either kill it with 'killall dnsmasq'"
    "${ECHO}" "or ignore this if you're okay with the version that is running"
else
    "${ECHO}" "Starting full DNSMasq..."
    "${DNSMASQ_FULL}" --except-interface=lo -r /tmp/resolv.conf
fi

"${ECHO}" "DNS Processes:"
"${PS}" aux | "${GREP}" -v "grep" | "${GREP}" -i dns
"${ECHO}" "DHCP Processes:"
"${PS}" aux | "${GREP}" -v "grep" | "${GREP}" -i dhcp
